### PR TITLE
fix protobuf and pyspark conflicts

### PR DESCRIPTION
**Pull request by andrewrreed**
https://jira.cloudera.com/browse/DSE-22559

### CODE REVIEW

**Comment by andrewrreed** [comment]
@melaniebeck Rather than upgrading `mlflow`, I downgraded `protobuf==3.20`, which then led to the pyspark dependency conflict. 

To summarize this issue (which I believe only happens on CDSW when cluster has spark):
1. MLflow has a built in integration with `sklearn` where it attempts to automatically log some Spark version info into the a model upon serializing it. 
```
    def to_dict(self):
        """Serialize the model to a dictionary."""
        res = {k: v for k, v in self.__dict__.items() if not k.startswith("_")}
        databricks_runtime = get_databricks_runtime()
        if databricks_runtime:
            res["databricks_runtime"] = databricks_runtime
        if self.signature is not None:
            res["signature"] = self.signature.to_dict()
        if self.saved_input_example_info is not None:
            res["saved_input_example_info"] = self.saved_input_example_info
        return res
```
2. To get that Spark info, it checks if code is being run in a databricks runtime. This is where the dependency conflict takes place...
```
def is_in_databricks_runtime():
    try:
        # pylint: disable=unused-import,import-error,no-name-in-module,unused-variable
        import pyspark.databricks

        return True
    except ModuleNotFoundError:
        return False
```
3. When running on cdsw with spark on the cluster, the `import pyspark.databricks` command returns a `TypeError` rather than a `ModuleNotFoundError` because technically its finding pyspark by accident:
image
4. To overcome this, we can just `pip install pyspark` so that `mlflow` finds the right `pyspark` (aka the library that does NOT have `pyspark.databricks`) and returns a `ModuleNotFoundError` (which the `is_in_databricks_runtime()` knows how to handle.
image

**Comment by andrewrreed** [comment]
I've tested this fix on both CDSW and CML PC, and can confirm it works, but it does introduce a dependency on `pyspark`... I suppose another fix could be to check `sys.path` for ` /opt/cloudera/parcels/CDH/lib/spark/python` and remove it before training any of the models.
image

Let me know your thoughts!

**Review by melaniebeck — COMMENTED** [review]
So if we include `pyspark` to circumvent the issue, do we need to change the .yaml file to include the spark add-on for use on CML?

**Comment by andrewrreed** [comment]
Nope, we don't actually need `pyspark` for any of its features... we just need pip not to find the `pyspark` that lives here: `/opt/cloudera/parcels/CDH/lib/spark/python`

So that can happen by installing pip installing pyspark which means pip finds it here first: `/home/cdsw/local/lib/python3.9/site-packages`

Or (I imagine) by removing `/opt/cloudera/parcels/CDH/lib/spark/python` from the path altogether (though I haven't tested this)

**Comment by MCGallaspy** [comment]
Is the intent of `is_in_databricks_runtime` function better achieved another way, aside from importing that module? Perhaps as suggested here: https://stackoverflow.com/questions/51329152/how-to-detect-databricks-environment-programmatically#comment119441427_55677636

See also: https://community.databricks.com/s/question/0D53f00001GHVLjCAP/how-to-find-databricks-runtime-version-of-the-cluster-in-an-init-script

**Comment by MCGallaspy** [comment]
Ok disregard, I see that function is not defined in our code.

**Comment by andrewrreed** [comment]
Yea sorry, I probably should have included where those functions live 😄

**Comment by melaniebeck** [comment]
Boo hiss to MLFlow for gappy error-handling. I think I'd rather install `pyspark` than try to fiddle around with the python path -- lots of room for error there. Especially if we don't need to do anything else. 

So I'm good with this and it sounds like this fix takes care of both [DSE-22559](https://jira.cloudera.com/browse/DSE-22559) and [DSE-21106](https://jira.cloudera.com/browse/DSE-21106)

**Pull request merged**
